
public class Texts {

    String loadingtex[] = {
        "System lädt",
        "System lädt.",
        "System lädt..",
        "System lädt...",
        "System lädt....",
        "Funktionen laden",
        "Funktionen laden.",
        "Funktionen laden..",
        "Funktionen laden...",
        "Funktionen laden....",
        "Methoden werden vorbereitet",
        "Methoden werden vorbereitet.",
        "Methoden werden vorbereitet..",
        "Methoden werden vorbereitet...",
        "Methoden werden vorbereitet....",
        "Methoden werden vorbereitet.....",
        "Methoden werden vorbereitet......",
        "Methoden werden vorbereitet.......",
        "Random generators laden",
        "Random generators laden",
        "Random generators laden",
        "Random generators laden",
        "Random generators laden",
        "Suchmaschine lädt",
        "Suchmaschine lädt",
        "Suchmaschine lädt",
        "Suchmaschine lädt",
        "Services laden",
        "Services laden",
        "Services laden",
        "Services laden",
        "Services laden",
        "Services laden",
        "Textbox lädt",
        "Textbox lädt",
        "Textbox lädt",
        "Textbox lädt",
        "Menü lädt",
        "Menü lädt",
        "Menü lädt",
        "Menü lädt",
        "Menü lädt[1]",
        "Menü lädt[1]",
        "Menü lädt[2]",
        "Menü lädt[2]",
        "Menü lädt[3]",
        "Menü lädt[3]",
        "Menü lädt[4]",
        "Menü lädt[4]",
        "Menü lädt[5]",
        "Menü lädt[5]",
        "Menü lädt[6]",
        "Menü lädt[6]",
        "Lädt",
        "Lädt",
        "Lädt",
        "Lädt",
        "Lädt",
        "Lädt",
        "",

    };

    String randomNames[] = {
        "Mighty",
        "Eto",
        "Knight",
        "Shredder",
        "Regilläf",
        "Lack",
        "Eran",
        "Linux",
        "Ainz",
        "Eman",
        "Questo",
        "Lunda",
        "Renek",
        "Retech",
        "Besteba",
        "Opane",
        "Zer",
        "Megatron",
        "Jason D.",
        "F",
        "G",
        "§",
        "W",
        "U",
        "S",
        "V",
        "§",
        "!",
        "W",
        "Der",
        "Eine",
        "Wie",
        "Terminator",
        "User",
        "Axe",
        "Lost",
        "High",
        "Java",
        "Geheim",
        "Ranger",
        "Raptor",
        "Akar",
        "Mars",
        "Rest",
        "Razor",
        "Zahl",
        "Yukin",
        "Bat",
        "Kämpfer",
        "Falle",
        "Rot",
        "Ist",
        "Aus",
        "In",
        "Rat",
        "Spike",
        "Klasse",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",

    };

    public String setTex(String[] a, int i) {

        return a[i];

    }
}
