import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;

public class Texts {
    ArrayList<String> loadingTex3 = new ArrayList<>(Arrays.asList("System lädt","Funktionen laden", "Methoden werden vorbereitet")); 


    String loadingtex[] = {
        "System lädt",
        "System lädt.",
        "System lädt..",
        "System lädt...",
        "System lädt....",
        "Funktionen laden",
        "Funktionen laden.",
        "Funktionen laden..",
        "Funktionen laden...",
        "Funktionen laden....",
        "Methoden werden vorbereitet",
        "Methoden werden vorbereitet.",
        "Methoden werden vorbereitet..",
        "Methoden werden vorbereitet...",
        "Methoden werden vorbereitet....",
        "Methoden werden vorbereitet.....",
        "Methoden werden vorbereitet......",
        "Methoden werden vorbereitet.......",
        "Random generators laden",
        "Random generators laden",
        "Random generators laden",
        "Random generators laden",
        "Random generators laden",
        "Suchmaschine lädt",
        "Suchmaschine lädt",
        "Suchmaschine lädt",
        "Suchmaschine lädt",
        "Services laden",
        "Services laden",
        "Services laden",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Textbox lädt",
        "Textbox lädt",
        "Textbox lädt",
        "Textbox lädt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Informationen werden gesammelt",
        "Lädt",

    };


    String randomNames[] = {
        "Mighty",
        "The",
        "Knight",
        "Shredder",
        "Zufälliger",
        "Lack",
        "Of",
        "Richtig",
        "Eins",
        "Name",
        "?",
        "Null",
        "Keiner",
        "Echter",
        "Bester",
        "OP",
        "Zer",
        "M",
        "D",
        "F",
        "G",
        "§",
        "W",
        "U",
        "S",
        "V",
        "§",
        "!",
        "W",
        "Der",
        "Eine",
        "Wie",
        "Terminator",
        "User",
        "Axe",
        "Lost",
        "Atakan",
        "Aswin",
        "Geheim",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",
        "Zufälliger",

    };
    public void texts(){
    }
}
