@startuml
start
:Anmelden;
:Menü: Karte anlegen;
if (Gibt es im Konto weniger als 10 Karten?) then
  -[#black]->
  :Ja;
 
   
else

  -[#black,dotted]->
  :Nein;

  -[#black,dotted]->

  -[#black,dotted]-> 
  end

endif
-[#gray,dotted]->
:Name eingeben(0-20C);
:Seltenheit auswählen[11];
:Damage eingeben(0-1000);
:HP eingeben(0-1000);
:Agilität eingeben(0-100);
:Element auswählen[9];
#LightGrey:(optional)Fähigkeit eingeben;
:Bestätigen;
:ID wird generiert;
end

start
:Anmelden;
:Menü: Meine Karten;
:Bestätigen;
end

start
:Anmelden;
:Menü: Karte bearbeiten;
:Name oder Index der Karte eingeben;
:Bestätigen;
:Kartekontrolle(wird kontrolliert, ob die Karte vorhanden ist oder nicht);
if (Nach Kontrolle) then
  -[#black]->
  :Ja;
  -[#green,dashed]-> gibt es im konto
  eine **Karte?**;
   
  :Der Benutzer erhält ein Menü mit allen Eigenschaften der gesuchten Karte;
else

  -[#black,dotted]->
  :Nein;

  -[#black,dotted]->

  :Funktion wird gestoppt;
  -[#black,dotted]->

endif
-[#gray,dotted]->
end

start
:Anmelden;
:Menü: Karte löschen;
:Name oder Index der Karte eingeben;
:Bestätigen;
:Kartekontrolle(wird kontrolliert, ob die Karte vorhanden ist oder nicht);
if (Nach Kontrolle) then
  -[#black]->
  :Ja;
  -[#green,dashed]-> gibt es im konto
  eine **Karte?**;
   
  :Karte wird gelöscht;
else

  -[#black,dotted]->
  :Nein;

  -[#black,dotted]->

  :Funktion wird gestoppt;
  -[#black,dotted]->

endif
-[#gray,dotted]->


end



@enduml
