@startuml
skinparam classAttributeIconSize 0

class App #DarkGray-Grey {
 s : SystemController




}

note left of App #MediumVioletRed\9932CC
 <b> Hier </b>beginnt
  das Programm 
end note


abstract ArraysList #DarkGray-Grey{
#search_Results : String[]
#rar : String[]
#elemente : String[]
#skills : String[]
#skills_Beschreibung : String[]
#rar_colors : Color[]
#elemente_colors : Color[]
#skills_colors : Color[]

 }
 
 class DataStore #DarkGray-Grey{
 ~name: String 
 ~password: int
 ~angemeldet: boolean
 ~ver : Boolean
 ~temp_KarteName : String
 ~temp_KarteSeltenheit : String
 ~temp_KarteDamage : String
 ~temp_KarteHP : String
 ~temp_KarteAgility : String
 ~temp_KarteElement : String
 ~temp_KarteID : String
 ~temp_KarteAbility : String    
 ~karten[] : Karte[9]
 +clearSavedTempCard() : void
}





class GUI #DarkGray-Grey {
 #frame: JFrame
 #box2 : JPanel
 #cardInfoMenu : JPanel      
 #cardsMenu : JPanel
 #infoPanel : JPanel
 #panel1 : JPanel
 #randomButton : JPanel
 #saveButton : JPanel
 #search_Box : JPanel
 #sync_Box : JPanel

 #cardInfoImage : JLabel
 #cardInfoText[] : JLabel[8]
 #infoI : JLabel
 #infoMes : JLabel
 #infoN : JLabel
 #iRandomButton : JLabel
 #iSaveButton: JLabel
 #infoText : JLabel
 #l: JLabel
 #l2: JLabel
 #optionI[] : JLabel[6]
 #randomCard[] : JLabel[6]
 #sec_Image : JLabel

 #backB: JButton
 #confirmButton: JButton
 #eRandomButton : JButton
 #eSaveButton: JButton
 #option[] : JButton[6]
 #searchB1: JButton
 #searchB2: JButton
 #searchB3: JButton
 #searchB4: JButton
 #showCardsButtons[] : JButton[10]
 #sync[] : JButton[3]

 #descriptionBox : JTextArea
 #infoD : JTextArea
 #sync_Text : JTextArea

 #texarea: JTextField

 ~r: double
 ~v: double

 texts : Texts
 arraysList : ArraysList
 dataStore : DataStore
 input : Input

}


class Input #DarkGray-Grey {
 +option_1(): void
 +keyPressed(java.awt.event.KeyEvent k) : void
 +keyReleased(java.awt.event.KeyEvent k) : void
 +keyTyped(java.awt.event.KeyEvent k) : void
}

class Karte #DarkGray-Grey {
 #Karte_Name: String
 #Karte_Seltenheit: String
 #Karte_Damage: String
 #Karte_HP: String
 #Karte_Agility: String
 #Karte_Element: String
 #Karte_Ability: String
 #Karte_ID: String

}

class SystemController #DarkGray-Grey {
-r1 : Random

-loadingValues[] : boolean[9]

-cardIndex : Byte
-d : Byte

-loading_height : int
-loading_width : int
-passwordNumbers : int
-r2 : int
-rd2 : int
-warnWait : int

-passwordController : String

+ei : JLabel
+wahlOption : JButton

 +karten[] : Karte[9]

 +loading() : void
 +clearBox() : void
 +addToBox(i : int) : void
 -ret() : void
 +randomName() : String
 -anmelden() : void
 +sync() : void
 +generateRarity() : String
 +generateNumber() : int
 -confirmName() : void
 +confirmCardName() : void
 +confirmCardRarity() : void
 +confirmCardDamage() : void
 +confirmCardHP() : void
 +confirmCardAgility() : void
 +confirmCardElement() : void
 +confirmCardAbility() : void
 +checkCards() : void
 +createCard(i : int) : void
 +option1_1() : void
 +clearSavedTempCard() : void
 +showOptions(b : boolean, n : int) : void
 +viewMenu() : void
 +saveCards() : void
 +editCard() : void
 +showEditPanel() : void
 +actionPerformed(java.awt.event.ActionEvent e) : void
}


class Texts #DarkGray-Grey {
+loadingTex: String[]
+randomNames: String[]
+setTex(a : String[], i : int) : String
}

class User #DarkGray-Grey {
 -name: String
 -password: int
 -angemeldet: boolean
}



SystemController "1" *-- "0..10" User
GUI "1" *-- "0..10" Texts
GUI "1" *-- "0..10" Input
App "1" *-- "0..10" SystemController
SystemController "1" *-- "0..10" GUI
DataStore -- Karte
Karte o-- User
GUI "1" *-- "0..10" DataStore
SystemController "1" *-- "0..10" Karte
GUI "1" *-- "0..10" ArraysList

ArraysList <|-- GUI
GUI <|-- SystemController


@enduml
