@startuml

Object karte1{

name = "Ice Dargon"
seltenheit = "Legendär"
karten ID = "1"
damage = "800"
hP = "900"
agilität = "75"
element = "Wasser"

}

object karte2{

    name = "Fire Dragon"
    seltenheit = "Legendär"
    karten ID = "4"
    damage = "850"
    hP = "950"
    agilität = "80"
    element = "Feuer"
}

Object user{

name = "Lukas"
passwort = "12345"
angemeldet = true

}

object "d1 : DataStore" {

    name = "Msallam"
    password = "23456"
    angemeldet = true
    ver = false


    temp_KarteName = "Fire Golem"
    temp_KarteSeltenheit = "Epic"
    temp_KarteDamage = "600"
    temp_KarteHP = "700"
    temp_KarteAgility = "50"
    temp_KarteElement = "Feuer"
    temp_KarteID = "2"
    temp_KarteAbility = "Premium"    


    re_KarteName = "Water Golem"
    re_KarteSeltenheit = "Epic"
    re_KarteDamage = "650"
    re_KarteHP = "750"
    re_KarteAgility = "55"
    re_KarteElement = "Wasser"
    re_KarteID = "3"
    re_KarteAbility = "Premium"
    karten[] = [Karte1; Karte2]

}

object systemcontroller{

    r1 = 10
    r2 = "0"
    d : Int
    karten[] = [Karte1; Karte2]


}

@enduml