@startuml 
' You can also declare:
group Karte anlegen [Karte anlegen]
    user -> "SystemController" : option1_1()
    SystemController -> "GUI" : (Hier wird der Gui gesagt, dass asufüllbare Textfeld anzuzeigen)
    GUI -> "SystemController" : 
    user -> "SystemController" : confirmCardName()
    SystemController -> "SystemController2" : showOptions(false) + addToBox(1)
    SystemController -> DataStore : (Hier wird temp_KarteName geändert)
    SystemController -> GUI : (Hier werden ActionCommands geändert(confirmButton,randomButton))
    DataStore -> SystemController
    GUI -> SystemController
    SystemController2 -> "SystemController" : 
    user -> "SystemController" : confirmCardRarity()
        SystemController -> DataStore : (Hier wird temp_KarteSeltenheit geändert)
    user -> "SystemController" : confirmCardDamage()
    user -> "SystemController" : confirmCardHP()
    user -> "SystemController" : confirmCardAgility()
    user -> "SystemController" : confirmCardElement()
    user -> "SystemController" : confirmCardAbility()
    SystemController -> "DataStore" : clearSavedTempCard()
@enduml